version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest  
    container_name: test_stuff
    secrets:
      - GENEZIO_TOKEN
    command: 
      - /bin/bash
      - -c
      - |
        echo -n $GENEZIO_TOKEN > ~/.geneziorc
        cat ~/.geneziorc

secrets:
  GENEZIO_TOKEN:
    external: true
