name: Users Unit Tests

on:
  push: 
    branches: [master, dev]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  stable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up 
        run: echo ${{ matrix.os }}
