name: blabla

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GENEZIO_TOKEN: ${{ secrets.GENEZIO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Execute tests from docker-compose
        run: docker-compose up --abort-on-container-exit --exit-code-from ubuntu
